% -------------------------------------------------------------------
%  Generated by MATLAB on 17-Feb-2017 08:33:33
%  MATLAB version: 8.5.0.197613 (R2015a)
% -------------------------------------------------------------------
saveVarsMat = load('psk_mod.mat');

A = 5;

f1 = 1;

f2 = 1;

t = saveVarsMat.t; % <1x1001 double> too many elements

u = saveVarsMat.u; % <1x1001 double> too many elements

v = saveVarsMat.v; % <1x1001 double> too many elements

x = saveVarsMat.x; % <1x1001 double> too many elements

clear saveVarsMat;
